/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bandtec.projeto.individual;

import java.awt.Color;
import java.util.Random;

/**
 *
 * @author Aluno
 */
public class TelaProgresso extends javax.swing.JFrame {

    /**
     * Creates new form TelaProgresso
     */
    public TelaProgresso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pgCpu = new javax.swing.JProgressBar();
        lblCpu = new javax.swing.JLabel();
        pgDisco = new javax.swing.JProgressBar();
        lblDisco = new javax.swing.JLabel();
        pgMemoria = new javax.swing.JProgressBar();
        lblMemoria = new javax.swing.JLabel();
        btnValores = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pgCpu.setBackground(new java.awt.Color(0, 255, 7));
        pgCpu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pgCpu.setForeground(new java.awt.Color(255, 255, 255));
        pgCpu.setStringPainted(true);

        lblCpu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCpu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCpu.setText("CPU:");

        pgDisco.setBackground(new java.awt.Color(0, 255, 7));
        pgDisco.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pgDisco.setForeground(new java.awt.Color(255, 255, 255));
        pgDisco.setStringPainted(true);

        lblDisco.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDisco.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDisco.setText("Disco:");

        pgMemoria.setBackground(new java.awt.Color(0, 255, 7));
        pgMemoria.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pgMemoria.setForeground(new java.awt.Color(255, 255, 255));
        pgMemoria.setStringPainted(true);

        lblMemoria.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblMemoria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMemoria.setText("Memória:");

        btnValores.setText("Fazer leitura dos dados");
        btnValores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValoresActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMemoria, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(lblDisco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnValores)
                            .addComponent(pgCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pgDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pgMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pgCpu, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pgDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pgMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnValores)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnValoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValoresActionPerformed
        // TODO add your handling code here:
        Random gerador = new Random();

        Integer aleatorioCpu = gerador.nextInt(101);
        Integer aleatorioDisco = gerador.nextInt(101);
        Integer aleatorioMemoria = gerador.nextInt(101);

        new Thread() {
            @Override
            public void run() {
                for (int i = 0; i < aleatorioCpu; i++) {
                    try {
                        sleep(10);
                        pgCpu.setValue(i);
                    } catch (InterruptedException e) {
                    }
                }
            }
        }.start();
        
        new Thread(){
            @Override
            public void run() {
                for (int i = 0; i < aleatorioDisco; i++) {
                    try {
                        sleep(10);
                        pgDisco.setValue(i);
                    } catch (InterruptedException e) {
                    }
                }
            }
        }.start();
        
        new Thread(){
            @Override
            public void run(){
                for (int i = 0; i < aleatorioMemoria; i++) {
                    try {
                        sleep(10);
                        pgMemoria.setValue(i);
                    } catch (InterruptedException e) {
                    }   
                }
            }
        }.start();
    }//GEN-LAST:event_btnValoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProgresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProgresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProgresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProgresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProgresso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnValores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCpu;
    private javax.swing.JLabel lblDisco;
    private javax.swing.JLabel lblMemoria;
    private javax.swing.JProgressBar pgCpu;
    private javax.swing.JProgressBar pgDisco;
    private javax.swing.JProgressBar pgMemoria;
    // End of variables declaration//GEN-END:variables
}
